# This file was generated by GoReleaser. DO NOT EDIT.
cask "nscale" do
  name "nscale"
  desc "The Nscale CLI tool"
  homepage "https://console.nscale.com"
  version "3.0.0-alpha.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nscale"
  bash_completion "completions/nscale.bash"
  zsh_completion "completions/nscale.zsh"
  fish_completion "completions/nscale.fish"

  on_macos do
    on_intel do
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v#{version}/nscale-cli_Darwin_x86_64.tar.gz"
      sha256 "ec4eb561b23f14798c016e45222fea8ed1e89571db109381fbecb262e63f48d7"
    end
    on_arm do
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v#{version}/nscale-cli_Darwin_arm64.tar.gz"
      sha256 "b919c7f9ea627aafaae3bfd758ceb26fe5766c8fae53fa244660e8513c6eb9b2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v#{version}/nscale-cli_Linux_x86_64.tar.gz"
      sha256 "da6dd3513ca113ba69dbdc3ef935994d54cfc7bf09d9fbf89f8538924f165d8c"
    end
    on_arm do
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v#{version}/nscale-cli_Linux_arm64.tar.gz"
      sha256 "b5c4ec6aad0401f22c53b360debad2b4243e82c1982444c87936d5624fb61973"
    end
  end

  # No zap stanza required
end
