# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NscaleAlpha < Formula
  desc "The Nscale CLI tool (ALPHA)"
  homepage "https://console.nscale.com"
  version "3.0.0-alpha.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v3.0.0-alpha.5/nscale-cli_Darwin_x86_64.tar.gz"
      sha256 "c6e07bb8e0fce05b585ba4c76f6036386df720aeec631cd1be71f293ff92de37"

      define_method(:install) do
        bin.install "nscale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v3.0.0-alpha.5/nscale-cli_Darwin_arm64.tar.gz"
      sha256 "f0a649805a1735d48d6cffb6c6b762bac580392eed7675d231b47e93f2b38bb1"

      define_method(:install) do
        bin.install "nscale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v3.0.0-alpha.5/nscale-cli_Linux_x86_64.tar.gz"
      sha256 "ae9c1c4d326f65ff1a821a0e0ba303159ff868b721a70dd964bc3f9a549ec9e1"
      define_method(:install) do
        bin.install "nscale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v3.0.0-alpha.5/nscale-cli_Linux_arm64.tar.gz"
      sha256 "de70a2debd149f04c87d2fcff5b2b8fc3b53c14d00f1d5dbef0a5e77de39b5ab"
      define_method(:install) do
        bin.install "nscale"
      end
    end
  end
end
