# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nscale < Formula
  desc "The Nscale CLI tool"
  homepage "https://console.nscale.com"
  version "1.0.1-beta1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v1.0.1-beta1/nscale-cli_Darwin_x86_64.tar.gz"
      sha256 "040ac033b8a8624f7cd780173b9f0cc336324565dfcef330ade6cdbb95c44fe1"

      def install
        bin.install "nscale"
      end
    end
    on_arm do
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v1.0.1-beta1/nscale-cli_Darwin_arm64.tar.gz"
      sha256 "7ab5d5fb08487b0adc99543f29a0e06234336d3fe0c346765fd2462c75ed4802"

      def install
        bin.install "nscale"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nscaledev/homebrew-tap/releases/download/v1.0.1-beta1/nscale-cli_Linux_x86_64.tar.gz"
        sha256 "ae0b12a9cc55fccab43ad2bd82fc04eead5caede471097514dd5856ef7b41633"

        def install
          bin.install "nscale"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nscaledev/homebrew-tap/releases/download/v1.0.1-beta1/nscale-cli_Linux_arm64.tar.gz"
        sha256 "008f12723116837b67dc90bea205ee92ea348fb916b68113cb11aadad0cf8c32"

        def install
          bin.install "nscale"
        end
      end
    end
  end
end
