# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NscaleAlpha < Formula
  desc "The Nscale CLI tool (ALPHA)"
  homepage "https://console.nscale.com"
  version "3.0.0-alpha.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v3.0.0-alpha.2/nscale-cli_Darwin_x86_64.tar.gz"
      sha256 "034120c5dae5e247eaa7008ba6f0cb55e15df2f268664c95f0df1ee057093668"

      def install
        bin.install "nscale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v3.0.0-alpha.2/nscale-cli_Darwin_arm64.tar.gz"
      sha256 "613f915560ec211517acf0ad8d2450c8c738509c5b33c7b15994c7111224a915"

      def install
        bin.install "nscale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v3.0.0-alpha.2/nscale-cli_Linux_x86_64.tar.gz"
      sha256 "0bf66d29da683fc16f1dc5973857189ea455627df08f4c41633f09b71368f3fb"
      def install
        bin.install "nscale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v3.0.0-alpha.2/nscale-cli_Linux_arm64.tar.gz"
      sha256 "d423e46670fd56c7d793e3659135b9660fb1db23681f2dc5905ad4c1498aefce"
      def install
        bin.install "nscale"
      end
    end
  end
end
