# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nscale < Formula
  desc "The Nscale CLI tool"
  homepage "https://console.nscale.com"
  version "3.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v3.2.0/nscale-cli_Darwin_x86_64.tar.gz"
      sha256 "213144a2b21bfcae02e61246adbd5edfaf282e2b3c2e1580eaa7a02f0f4c4d95"

      define_method(:install) do
        bin.install "nscale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v3.2.0/nscale-cli_Darwin_arm64.tar.gz"
      sha256 "82ee8b72d90527959aa297b464f34c3d304229c0b4d71e4e7066a257a7958bd4"

      define_method(:install) do
        bin.install "nscale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v3.2.0/nscale-cli_Linux_x86_64.tar.gz"
      sha256 "fb017b31baf130b4a06b4c98f1818372ed8f7f3f240c7e3b291663c62d675222"
      define_method(:install) do
        bin.install "nscale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v3.2.0/nscale-cli_Linux_arm64.tar.gz"
      sha256 "c6dfd16b45a83c2cff1e71a0b724a5c52c1925146627bfe3ac0a962894c05083"
      define_method(:install) do
        bin.install "nscale"
      end
    end
  end
end
