# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nscale < Formula
  desc "The Nscale CLI tool"
  homepage "https://console.nscale.com"
  version "4.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v4.0.1/nscale-cli_Darwin_x86_64.tar.gz"
      sha256 "caf19b11b571ba8bd7fc2c11a5cdd9596c31c70fbf5a8ad789417424e8781b00"

      define_method(:install) do
        bin.install "nscale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v4.0.1/nscale-cli_Darwin_arm64.tar.gz"
      sha256 "8d6fef5b8c20a2ad9a88aa29baef8cf3f07b8d65aa2a51586347f9d02389e7e2"

      define_method(:install) do
        bin.install "nscale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v4.0.1/nscale-cli_Linux_x86_64.tar.gz"
      sha256 "ae3edc8a2ad62393d1961122fc43b5edbf3fdc648240d5aa61cbbf54164c13cd"
      define_method(:install) do
        bin.install "nscale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nscaledev/homebrew-tap/releases/download/v4.0.1/nscale-cli_Linux_arm64.tar.gz"
      sha256 "d006954a7ba6c6e42c1c0069283d363dc70a49b1b7dd5212768dae9fb38c8077"
      define_method(:install) do
        bin.install "nscale"
      end
    end
  end
end
